services:
  restate:
    image: docker.io/restatedev/restate:latest
    container_name: restate-server
    ports:
      - "8080:8080"
      - "9070:9070"
    volumes:
      - restate-data:/restate-data

volumes:
  restate-data:
